# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='curr',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='currname',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='nationality_name',
        ),
        migrations.AddField(
            model_name='currency',
            name='code_dub',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='code_leb',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality',
            name='code_dub',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality',
            name='code_leb',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
