# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171002_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='monitoring_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='provider_ratelist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='monitoring_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='provider_ratelist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='monitoring_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='provider_ratelist',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='monitoring_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='provider_ratelist',
            field=models.IntegerField(),
        ),
    ]
