# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171002_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
    ]
