# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171002_1559'),
        ('app', '0007_auto_20171002_1319'),
    ]

    operations = [
    ]
