# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171003_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitybond',
            name='monitoring_type',
        ),
        migrations.RemoveField(
            model_name='securityfutures',
            name='monitoring_type',
        ),
        migrations.RemoveField(
            model_name='securityoption',
            name='monitoring_type',
        ),
        migrations.RemoveField(
            model_name='securityshare',
            name='monitoring_type',
        ),
    ]
