# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171004_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitybond',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='securityfutures',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='securityoption',
            name='bank_reference',
        ),
        migrations.RemoveField(
            model_name='securityshare',
            name='bank_reference',
        ),
    ]
