# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171010_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
    ]
