# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171010_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
    ]
