# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20171010_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='deposit_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='deposit_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='deposit_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='deposit_place',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
        ),
    ]
