# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20171010_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='main_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='main_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='mar_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='mar_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='main_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='main_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='mar_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='mar_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='main_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='main_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='mar_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='mar_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='main_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='main_short_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='mar_lng_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='mar_short_position',
            field=models.FloatField(),
        ),
    ]
