# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20171011_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='deposit_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='deposit_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='deposit_place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='deposit_place',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='DepositPlace',
        ),
    ]
