# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20171012_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='subtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='subtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='subtype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='subtype',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
    ]
