# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20171012_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='DepositPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='QuotationPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='RateListProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'subtypes',
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='TradingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.CreateModel(
            name='TradingCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='ratelist',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='ratelist',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='ratelist',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='multiplier_for_online_prices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='ratelist',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TradingCenter'),
        ),
        migrations.AddField(
            model_name='securitybond',
            name='quotation_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityfutures',
            name='quotation_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityoption',
            name='quotation_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityshare',
            name='quotation_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.QuotationPlace'),
            preserve_default=False,
        ),
    ]
