# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20171012_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitybond',
            name='ratelist',
        ),
        migrations.RemoveField(
            model_name='securityfutures',
            name='ratelist',
        ),
        migrations.RemoveField(
            model_name='securityoption',
            name='ratelist',
        ),
        migrations.RemoveField(
            model_name='securityshare',
            name='ratelist',
        ),
    ]
