# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20171013_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code_dub',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code_leb',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='circular',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='circular',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='circular',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='circular',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
