# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20171016_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DepositPlace'),
        ),
    ]
