# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20171016_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name', 'code_leb', 'code_dub'), 'verbose_name_plural': 'categories'},
        ),
    ]
