# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-03 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20180430_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_leb', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('code_dub', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name', 'code_leb', 'code_dub'),
            },
        ),
    ]
