# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitybond',
            name='is_dividend_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityfutures',
            name='is_dividend_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityoption',
            name='is_dividend_futures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityshare',
            name='is_dividend_futures',
            field=models.BooleanField(default=False),
        ),
    ]
