# Generated by Django 2.0.5 on 2018-05-21 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitybond',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nationality'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securitybond',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nationality'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityfutures',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nationality'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityoption',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCenter'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='asset_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.AssetAllocation'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Currency'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='deposit_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.DepositPlace'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nationality'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Nature'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='provider_ratelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.RateListProvider'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='quotation_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.QuotationPlace'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='subtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Subtype'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='trading_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCategory'),
        ),
        migrations.AlterField(
            model_name='securityshare',
            name='trading_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TradingCenter'),
        ),
    ]
