# coding: utf-8
from sqlalchemy import Column, DateTime, Float, Index, Integer, Numeric, SmallInteger, String
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class TITRE(Base):
    __tablename__ = 'TITRE'
    __table_args__ = (
        Index('_dta_index_TITRE_23_34099162__K1_3', 'TIT_COD', 'TIT_NOM'),
        Index('Options', 'TIT_TYP_TIT_COD', 'TIT_OPTIONS'),
        Index('_dta_index_TITRE_20_34099162__K1_34_38', 'TIT_COD', 'TIT_O_MOD_COD', 'TIT_NB_UNITE'),
        Index('putcall', 'TIT_PUT', 'TIT_CALL'),
        Index('_dta_index_TITRE_24_34099162__K1_K5_3_38_64', 'TIT_COD', 'TIT_TYP_TIT_COD', 'TIT_NOM', 'TIT_NB_UNITE', 'TIT_ISIN_COD')
    )

    TIT_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), primary_key=True)
    TIT_CIR = Column(String(4, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_NOM = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_DEV_COD = Column(String(2, 'SQL_Latin1_General_CP1256_CI_AS'), index=True)
    TIT_TYP_TIT_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_STY_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_NAT_TIT_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_CAT_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_MAR_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_NAT_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_PCE_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_DEP_COD = Column(String(6, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_LST_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FIXING = Column(Integer)
    TIT_FIX_1 = Column(String(5, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FIX_2 = Column(String(5, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FRAIS = Column(Integer)
    TIT_FR1 = Column(Float(53))
    TIT_FR1_FFA = Column(Float(53))
    TIT_FR1_DEP = Column(Float(53))
    TIT_FR2 = Column(Float(53))
    TIT_FR2_FFA = Column(Float(53))
    TIT_FR2_DEP = Column(Float(53))
    TIT_FR3 = Column(Float(53))
    TIT_FR3_FFA = Column(Float(53))
    TIT_FR3_DEP = Column(Float(53))
    TIT_FR4 = Column(Float(53))
    TIT_FR4_FFA = Column(Float(53))
    TIT_FR4_DEP = Column(Float(53))
    TIT_FR5 = Column(Float(53))
    TIT_FR5_FFA = Column(Float(53))
    TIT_FR5_DEP = Column(Float(53))
    TIT_OCCUPE = Column(Integer)
    TIT_O_MOD_COD = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), nullable=False)
    TIT_SHOW = Column(Integer)
    TIT_HOLDER = Column(Integer)
    TIT_OPTIONS = Column(Integer, index=True)
    TIT_NB_UNITE = Column(Numeric(25, 2))
    TIT_DAT_MAT = Column(DateTime)
    TIT_SEQ = Column(String(6, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR1_FFACPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR1_DEPCPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR2_FFACPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR2_DEPCPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR3_FFACPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR3_DEPCPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR4_FFACPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR4_DEPCPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR5_FFACPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_FR5_DEPCPT = Column(String(15, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_CHART_ACC = Column(String(4, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_REU_COD = Column(String(50, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_DIV_CHART = Column(String(4, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_MAR = Column(Integer, nullable=False)
    TIT_MAR_LN = Column(Numeric(25, 4), nullable=False)
    TIT_MAR_SH = Column(Numeric(25, 4), nullable=False)
    TIT_UPD = Column(SmallInteger)
    TIT_STRIKE = Column(Float(53))
    TIT_UNDERLYING = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), index=True)
    TIT_PUT = Column(SmallInteger)
    TIT_CALL = Column(SmallInteger)
    TIT_FUTUR = Column(SmallInteger, index=True)
    TIT_DEV_COD2 = Column(String(2, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_ISIN_COD = Column(String(20, 'SQL_Latin1_General_CP1256_CI_AS'))
    Tit_dep_Ref = Column(String(25, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_DEV_COD1 = Column(String(2, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_ISSUER = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_DESC = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_RATIO = Column(Numeric(18, 7))
    TIT_CATEG = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), nullable=False)
    TIT_TRADING_CATEG = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), nullable=False)
    TIT_RATE_LIST = Column(Integer, nullable=False)
    Tit_Asset_Cod = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'), nullable=False)
    TIT_FORWARD = Column(Integer, nullable=False)
    TIT_FWD_SPOT = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_TREATED_ONLINE = Column(Integer, nullable=False)
    TIT_FIRST_NOTICE_DAT = Column(DateTime)
    TIT_PIP_VALUE = Column(Numeric(16, 7), nullable=False)
    TIT_ONLINE_RATE_MULTIPLIER = Column(Numeric(27, 5))
    TIT_MAR_DEV = Column(String(2, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_MONITOR_TYPE = Column(Integer, nullable=False)
    TIT_CR_RATE1 = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_CR_RATE2 = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_CR_RATE3 = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_TTG_COD = Column(Numeric(10, 0), nullable=False)
    TIT_MAR_LN_MC = Column(Numeric(25, 4))
    TIT_MAR_SH_MC = Column(Numeric(25, 4))
    TIT_UPD_LOGIN = Column(String(10, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_UPD_ACTION = Column(String(1, 'SQL_Latin1_General_CP1256_CI_AS'))
    TIT_UPD_LAST_DATE = Column(DateTime)
    TIT_TICKET_PROVIDER_CODE = Column(Integer)
    TIT_TICKET_PROVIDER_SYMBOL = Column(String(100, 'SQL_Latin1_General_CP1256_CI_AS'))
